# Generated by Django 6.0.7 on 2026-07-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transaction_merchant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyincome',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='NGN', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='NGN', max_length=10),
        ),
    ]
